### ISSUE TITLE
I have a error when using two function: assign_cdr_labels() and build_msa(), just like:

### ISSUE THREAD

**Issue by Coke-Zhang** [jlparkI/AntPack#19]

**Comment by jlparkI** [comment]
There is no bug -- just a change in the API between older versions and v0.3.6.1. This is unfortunately a breaking change which we will avoid in future versions, the API should now be fairly stable. If you want to see what version you have installed, from the command line, run:
```
pip show antpack
```

In older versions, `build_msa` took two arguments, in v0.3.6.1 and later it takes three arguments as indicated in the docs. The docs online show usage for v0.3.6.1, and the examples in the docs are using v0.3.6.1. If you want to run one of the examples in the docs exactly as shown, you will need to use version 0.3.6.1 or later. To do this, from the command line, type:

```
pip install --upgrade antpack
```

We recommend updating to the latest version in any case because it is faster and includes a bug fix.
