### ISSUE TITLE
Annotate germline information

### ISSUE THREAD

**Issue by ywilke** [jlparkI/AntPack#2]
Are there plans to add the ability to annotate the species, V and J gene like when using ANARCI with the `assign_germline` option?

**Comment by jlparkI** [comment]
Yes, we would like to add V and J gene annotation in one of the next two releases, although there are a few details we need to figure out about what this should look like.

Of the existing open source numbering tools (AbNum, AbRSA, ANARCI) that I am aware of, I think ANARCI is the only one that does this and it defaults to considering human and mouse alignments unless the user indicates another species of origin, in which case the specified species of origin is used. 

Most probably we will add a separate function under SingleChainAnnotator where the user can supply a sequence, indicate the species of interest, and get V / J gene assignments for that. We could set this up (a) so they can either retrieve numbering at the same time or (b) so that the function requires an already numbered sequence as input -- probably (a) is preferable.

**Comment by jlparkI** [comment]
A tool for vj gene assignment, together with a couple of other new tools, have been added in the new version (v0.2.0) which will be released tomorrow and is still in develop; just finishing adding more unit tests now. I am therefore closing this issue since this is now resolved.

**Comment by jlparkI** [comment]
An interesting side note: ANARCI seems to have an occasional bug for assigning germlines. Take for example this sequence:

VQLLESGGGLVQPGGSLRLSCAASGHYIMMWVRQAPGKGLEWVSGIYGGITVYADSVKGRFTISRDNSKNTLYLQMNSLRAEDTAVYYCAYRRIRDEFDIWGQGTMVTVSS

Both ANARCI and AntPack assign the same numbering. However, ANARCI internally seems to be using a _different_ arrangement to assign a germline than it is reporting for the final numbering for this sequence. Externally, the IMGT numbering it assigns seems to be such that the sequence is like this:

-VQLLESGG-GLVQPGGSLRLSCAASGH--------YIMMWVRQAPGKGLEWVSGIYG----GITVYADSVK-GRFTISRDNSKNTLYLQMNSLRAEDTAVYYCAYRRIR--DEFDIWGQGTMVTVSS

Internally, however, it seems to be using this to assign germline:

-VQLLESGG-GLVQPGGSLRLSCAASGHYI--------MMWVRQAPGKGLEWVSGIYGG----ITVYADSVK-GRFTISRDNSKNTLYLQMNSLRAEDTAVYYCAY--RRIRDEFDIWGQGTMVTVSS

which is not consistent with their final numbering. This is however awkward because it means that in a few cases the V genes assigned by ANARCI seem to be _different_ from what you would conclude based on their numbering. Not sure how common this problem is. It is not my package so I am not going to investigate in more depth at this time though....
